/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Front;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Haseeb
 */
public class MyContactForm extends javax.swing.JFrame {

    /**
     * Creates new form MyContactForm
     */
    public static int currentUserId;
    int pos=0;
    public MyContactForm() {
        initComponents();
        populateJtable();
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.BLACK);
        jTable1.setSelectionBackground(Color.gray);
        JTableHeader th=jTable1.getTableHeader();
        th.setForeground(Color.BLUE);
        th.setFont(new Font("Tahoma", Font.BOLD, 15));
        
       System.out.println(currentUserId+"From Contact ");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMn = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2UserName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxGroup = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldArea = new javax.swing.JTextField();
        jButtonEditContact = new javax.swing.JButton();
        jTextFieldID = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldFirstName2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxGroup1 = new javax.swing.JComboBox();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldArea1 = new javax.swing.JTextField();
        jButtonAddContact1 = new javax.swing.JButton();
        jTextFieldFirstName3 = new javax.swing.JTextField();
        jTextFieldLastName = new javax.swing.JTextField();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddContact2 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldFirstName4 = new javax.swing.JTextField();
        jButtonDeleteContact1 = new javax.swing.JButton();
        jButton1First = new javax.swing.JButton();
        jButton2Last = new javax.swing.JButton();
        jButton3Previous = new javax.swing.JButton();
        jButton4Next = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMn.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMn.setText("-");
        jLabelMn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MY CONTACTS ");

        jLabel2UserName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2UserName.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2UserName.setText("Username");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2UserName)
                .addGap(309, 309, 309)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 416, Short.MAX_VALUE)
                .addComponent(jLabelMn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClose)
                    .addComponent(jLabelMn)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2UserName))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 0, 51));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 310, 100, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ID:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 20, 100, 30);

        jTextFieldEmail.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldEmail);
        jTextFieldEmail.setBounds(120, 220, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 120, 100, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 170, 100, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(10, 220, 100, 30);

        jComboBoxGroup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGroup.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family ", "Friends ", "Work", " " }));
        jComboBoxGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGroupActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxGroup);
        jComboBoxGroup.setBounds(120, 270, 160, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(330, 30, 30, 230);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Group");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 270, 100, 30);

        jTextFieldArea.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldArea.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jPanel2.add(jTextFieldArea);
        jTextFieldArea.setBounds(20, 360, 240, 70);

        jButtonEditContact.setBackground(new java.awt.Color(0, 0, 255));
        jButtonEditContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditContact.setForeground(new java.awt.Color(204, 204, 255));
        jButtonEditContact.setText("Edit");
        jButtonEditContact.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEditContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditContactActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonEditContact);
        jButtonEditContact.setBounds(210, 460, 80, 30);

        jTextFieldID.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldID);
        jTextFieldID.setBounds(120, 20, 160, 30);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Text Area");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(370, 40, 100, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("First Name");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(10, 30, 100, 30);

        jTextFieldFirstName2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFirstName2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldFirstName2);
        jTextFieldFirstName2.setBounds(120, 90, 160, 30);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Last Name");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 90, 100, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(10, 140, 100, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(10, 190, 100, 30);

        jComboBoxGroup1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxGroup1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Family ", "Friends ", "Work", " " }));
        jComboBoxGroup1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGroup1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxGroup1);
        jComboBoxGroup1.setBounds(120, 240, 160, 30);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator2);
        jSeparator2.setBounds(330, 30, 30, 230);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Group");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(10, 240, 100, 30);

        jTextFieldArea1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.add(jTextFieldArea1);
        jTextFieldArea1.setBounds(380, 90, 240, 130);

        jButtonAddContact1.setBackground(new java.awt.Color(153, 102, 255));
        jButtonAddContact1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddContact1.setForeground(new java.awt.Color(204, 204, 255));
        jButtonAddContact1.setText("ADD");
        jButtonAddContact1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContact1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonAddContact1);
        jButtonAddContact1.setBounds(910, 380, 80, 30);

        jTextFieldFirstName3.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFirstName3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel3.add(jTextFieldFirstName3);
        jTextFieldFirstName3.setBounds(120, 30, 160, 30);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(0, 0, 0, 0);

        jTextFieldLastName.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldLastName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLastNameActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldLastName);
        jTextFieldLastName.setBounds(120, 120, 160, 30);

        jTextFieldPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldPhoneNumber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPhoneNumberActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldPhoneNumber);
        jTextFieldPhoneNumber.setBounds(120, 170, 160, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(340, 40, 720, 440);

        jButtonAddContact2.setBackground(new java.awt.Color(32, 163, 32));
        jButtonAddContact2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddContact2.setForeground(new java.awt.Color(204, 204, 255));
        jButtonAddContact2.setText("Add");
        jButtonAddContact2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAddContact2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddContact2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAddContact2);
        jButtonAddContact2.setBounds(20, 460, 80, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("First Name");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(10, 70, 100, 30);

        jTextFieldFirstName4.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldFirstName4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel2.add(jTextFieldFirstName4);
        jTextFieldFirstName4.setBounds(120, 70, 160, 30);

        jButtonDeleteContact1.setBackground(new java.awt.Color(255, 0, 0));
        jButtonDeleteContact1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonDeleteContact1.setForeground(new java.awt.Color(204, 204, 255));
        jButtonDeleteContact1.setText("Delete");
        jButtonDeleteContact1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeleteContact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteContact1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeleteContact1);
        jButtonDeleteContact1.setBounds(120, 460, 80, 30);

        jButton1First.setText("<<");
        jButton1First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1FirstActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1First);
        jButton1First.setBounds(610, 490, 49, 23);

        jButton2Last.setText(">>");
        jButton2Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2LastActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2Last);
        jButton2Last.setBounds(860, 490, 49, 23);

        jButton3Previous.setText(">");
        jButton3Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3PreviousActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3Previous);
        jButton3Previous.setBounds(780, 490, 41, 23);

        jButton4Next.setText("<");
        jButton4Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4NextActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4Next);
        jButton4Next.setBounds(690, 490, 41, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void populateJtable(){
        contactQuery cq=new contactQuery();
        ArrayList<contact>ctList =cq.contactList(currentUserId);
        String[] colNames={"ID","First Name "," Last Name ","Group ","Phone","Email","Address"};
        Object[][] rows=new Object[ctList.size()][7];
        for(int i=0;i<ctList.size();i++){
            rows[i][0]=ctList.get(i).getCid();
            rows[i][1]=ctList.get(i).getFirstName();
            rows[i][2]=ctList.get(i).getLastName();
            rows[i][3]=ctList.get(i).getGroup();
            rows[i][4]=ctList.get(i).getPhone();
            rows[i][5]=ctList.get(i).getEmail();
            rows[i][6]=ctList.get(i).getAddress();
            
            MyModel mmd=new MyModel(rows,colNames) {} ;
            
            jTable1.setModel(mmd);
            jTable1.setRowHeight(50);
   }
  }
    private void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabelCloseMouseClicked

    private void jLabelMnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMnMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);

    }//GEN-LAST:event_jLabelMnMouseClicked

    private void jComboBoxGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGroupActionPerformed
    public void refreshJtable(){
//        jTable1.setModel(new DefaultTableModel(null,Object[]{"ID","First Name "," Last Name ","Group ","Phone","Email","Address"}));
       jTable1.setModel(new DefaultTableModel());
       populateJtable();
       
    }  
    public void clearFields(){
        jTextFieldID.setText("");
        jTextFieldFirstName4.setText("");
        jTextFieldLastName.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldArea.setText("");
        jTextFieldEmail.setText("");
        jComboBoxGroup.setSelectedIndex(0);
        
    }
    public void showData(int index)   {
        jTextFieldID.setText(jTable1.getValueAt(index, 0).toString());
jTextFieldFirstName4.setText(jTable1.getValueAt(index, 1).toString());
jTextFieldLastName.setText(jTable1.getValueAt(index, 2).toString());

//    group phone email address 
jComboBoxGroup.setSelectedItem(jTable1.getValueAt(index,3));
jTextFieldPhoneNumber.setText(jTable1.getValueAt(index,4).toString());
jTextFieldEmail.setText(jTable1.getValueAt(index,5).toString());
//jTextFieldID.setText(jTable1.getValueAt(rowIndex,0).toString());
jTextFieldArea.setText(jTable1.getValueAt(index,6).toString());


    }
    
    private void jButtonEditContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditContactActionPerformed
      //  this method will update contact information table
        if(!jTextFieldID.equals(" ")){
       
        
        int ID=Integer.valueOf(jTextFieldID.getText());
        String firstName=jTextFieldFirstName4.getText();
        String lastName=jTextFieldLastName.getText();
        String phone=jTextFieldPhoneNumber.getText();
        String address=jTextFieldArea.getText();
        String email=jTextFieldEmail.getText();
        String groupc= jComboBoxGroup.getSelectedItem().toString();
        if(jTextFieldID.equals(null) || jTextFieldFirstName4.equals(null) ||jTextFieldPhoneNumber.equals(null)){
        JOptionPane.showMessageDialog(null," You Must Select Atleast  ID  Name and Phone Number  ");
        clearFields();
        
    }
        contact c=new contact(ID, firstName, lastName, groupc, phone, email, address, currentUserId);
        contactQuery cq=new contactQuery();
//        cq.insertContact(c);
        cq.updateContact(c);
        refreshJtable();
        clearFields();
        }else{
                 JOptionPane.showMessageDialog(null, " Select a Contact From a Table ");
        }
    }//GEN-LAST:event_jButtonEditContactActionPerformed

    private void jComboBoxGroup1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGroup1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGroup1ActionPerformed

    private void jButtonAddContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddContact1ActionPerformed

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLastNameActionPerformed

    private void jTextFieldPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPhoneNumberActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        //display selected JTable row data
        
      // get selected row index        
        int rowIndex=jTable1.getSelectedRow();
jTextFieldID.setText(jTable1.getValueAt(rowIndex, 0).toString());
jTextFieldFirstName4.setText(jTable1.getValueAt(rowIndex, 1).toString());
jTextFieldLastName.setText(jTable1.getValueAt(rowIndex, 2).toString());

//    group phone email address 
jComboBoxGroup.setSelectedItem(jTable1.getValueAt(rowIndex,3));
jTextFieldPhoneNumber.setText(jTable1.getValueAt(rowIndex,4).toString());
jTextFieldEmail.setText(jTable1.getValueAt(rowIndex,5).toString());
//jTextFieldID.setText(jTable1.getValueAt(rowIndex,0).toString());
jTextFieldArea.setText(jTable1.getValueAt(rowIndex,6).toString());


                
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonAddContact2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddContact2ActionPerformed
        // TODO add your handling code here:
   
               int ID=Integer.valueOf(jTextFieldID.getText());
        String firstName=jTextFieldFirstName4.getText();
        String lastName=jTextFieldLastName.getText();
        String phone=jTextFieldPhoneNumber.getText();
        String address=jTextFieldArea.getText();
        String email=jTextFieldEmail.getText();
        String groupc= jComboBoxGroup.getSelectedItem().toString();
             if(jTextFieldID.equals(null) || jTextFieldFirstName4.equals(null) ||jTextFieldPhoneNumber.equals(null)){
        JOptionPane.showMessageDialog(null," You Must Select Atleast  ID  Name and Phone Number  ");
    }
        contact c=new contact(ID, firstName, lastName, groupc, phone, email, address, currentUserId);
        contactQuery cq=new contactQuery();
     cq.insertContact(c);
             refreshJtable();
       clearFields();
    }//GEN-LAST:event_jButtonAddContact2ActionPerformed

    private void jButtonDeleteContact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteContact1ActionPerformed
        // TODO add your handling code here:
        if(!jTextFieldID.equals("")){
        int id=Integer.valueOf(jTextFieldID.getText());
        contactQuery cq=new contactQuery();
        cq.deleteContact(id);
        refreshJtable();
        clearFields();}
        else{
            JOptionPane.showMessageDialog(null," Select Contact From a Table ");
            
        }
    }//GEN-LAST:event_jButtonDeleteContact1ActionPerformed

    private void jButton1FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1FirstActionPerformed
        // TODO add your handling code here:
        pos=0;
        showData(pos);
        
    }//GEN-LAST:event_jButton1FirstActionPerformed

    private void jButton2LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2LastActionPerformed
        // TODO add your handling code here:
        pos=jTable1.getRowCount() -1 ;
        showData(pos);
        
    }//GEN-LAST:event_jButton2LastActionPerformed

    private void jButton4NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4NextActionPerformed
        // TODO add your handling code here:
        pos++;
         showData(pos);
    }//GEN-LAST:event_jButton4NextActionPerformed

    private void jButton3PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3PreviousActionPerformed
        // TODO add your handling code here:
        pos--;
         showData(pos);
        
    }//GEN-LAST:event_jButton3PreviousActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyContactForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyContactForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1First;
    private javax.swing.JButton jButton2Last;
    private javax.swing.JButton jButton3Previous;
    private javax.swing.JButton jButton4Next;
    private javax.swing.JButton jButtonAddContact1;
    private javax.swing.JButton jButtonAddContact2;
    private javax.swing.JButton jButtonDeleteContact1;
    private javax.swing.JButton jButtonEditContact;
    private javax.swing.JComboBox<String> jComboBoxGroup;
    private javax.swing.JComboBox<String> jComboBoxGroup1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel2UserName;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelMn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldArea1;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFirstName2;
    private javax.swing.JTextField jTextFieldFirstName3;
    private javax.swing.JTextField jTextFieldFirstName4;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldLastName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
